apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
  template:
    metadata:
      labels: 
        app: demo-voting-app
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
  - port: 6379
    name: redis-something
    targetPort: 6379
  selector:
     name: redis-pod
     app: demo-voting-app